# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 688ab7c51f726707d6a4148790703ecd2e1ddbfa5c3f3568c4d5d6bc025611dd1c63290cd34b049ec8e81ee5a896357388c9752533617173ffe9d589edbfdc7f

test:
  secret_key_base: d3ebc024716c3c9674e5935d799957f10fec0ccd32b22cb4f462f7ba5199c01787c8df67168a8e4dbdec8e66a9628677f4a5f5bb7132660760381f7ce4418cd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
